/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.globaldesktop;

import com.org.globaldesktop.master.*;
import com.org.globaldesktop.transactions.InvoiceEntry;
import com.org.globaldesktop.transactions.PrintReport;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class index extends javax.swing.JFrame {

    // **********Master Objects************
    Vehicle vehicle;
    Vendor vendor;
    Employee employee;
    InvoiceEntry invoiceEntry;
    PrintReport printReport;

    public index() {
        try {
            // UIManager.setLookAndFeel("lUIManager.getSystemLookAndFeelClassName()");
//            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            this.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("images/logo.png"));
        } catch (Exception e) {
        }
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Unique Medi+ - Logo1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        jMenu1.setText("Master");

        jMenuItem1.setText("Vehicle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Employee");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem27.setText("Bank");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenuItem2.setText("Vendor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Invoice Entry");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("Exit");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventory");

        jMenu7.setText("Purchase");

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem17.setText("Distributor -Purchase Order");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem11.setText("Product- Purchase Order");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem18.setText("Purchase Return");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem23.setText("Purchase Invoice");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem23);

        jMenu2.add(jMenu7);
        jMenu2.add(jSeparator1);

        jMenu8.setText("Sales");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setText("Sales Order");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem21.setText("Counter Sale");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem19.setText("Retailer Sale");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem19);

        jMenuItem20.setText("Sales Return");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem28.setText("Counter Return");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem28);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Stock");

        jMenuItem24.setText("Damage Stock");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuItem25.setText("Expiry Stock");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem25);

        jMenu6.setText("Stock Updation");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem13.setText("Material Inward With PO");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Material Inward Without PO");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenu3.add(jMenu6);

        jMenuItem32.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem32.setText("Product Search");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem32);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Account");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem8.setText("Debit Note");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem15.setText("Credit Note");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem29.setText("Short Balancesheet");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem29);

        jMenuItem30.setText("Bounce Cheques");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem30);

        jMenuItem31.setText("Pending Amount");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem31);

        jMenuItem33.setText("Customer Cash Payment");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem33);

        jMenuItem35.setText("Vouchers");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem35);

        jMenuItem39.setText("Bank Transaction");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem39);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Account Setting");

        jMenuItem10.setText("View Profile");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem22.setText("Change Password");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem22);

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem26.setText("Calculator");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem26);

        jMenuItem6.setText("Notepad");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem12.setText("Short Cuts");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu10.setText("Reports");

        jMenuItem34.setText("Product Reports");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem34);

        jMenuItem36.setText("Customized Product Reports");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem36);

        jMenuItem40.setText("Purchase Reports");
        jMenu10.add(jMenuItem40);

        jMenuItem37.setText("Stock Reports");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem37);

        jMenuItem38.setText("Account Reports");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem38);

        jMenuItem7.setText("Invoice Report");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem7);

        jMenuBar1.add(jMenu10);

        jMenu9.setText("Log Off");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdp, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void demoversion() {
//        Calendar expireDate = Calendar.getInstance();
//// January is 0 (y, m, d)
//expireDate.set(2012, 5, 25);
//// Get current date and compare
//if (Calendar.getInstance().after(expireDate)) {
//  // Die
//    
//  Trailversion t=new Trailversion();
//    t.setVisible(rootPaneCheckingEnabled);
// 
//}
    }
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
//     jdp.removeAll();
//        Debtorsobj = new Account.Debtors(this, true);
//        
//        jdp.add(Debtorsobj);
//        Debtorsobj.setVisible(true);
//        Debtorsobj.setPreferredSize(getMaximumSize());
//        
//        Debtorsobj.setClosable(true);
//try {
//            Debtorsobj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jdp.removeAll();
        vehicle = new Vehicle(this, true);
        jdp.add(vehicle);
        vehicle.setVisible(true);
        vehicle.setPreferredSize(getMaximumSize());
        vehicle.setClosable(true);
        try {
            vehicle.setMaximum(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jdp.removeAll();
        employee = new Employee(this, true);
        jdp.add(employee);
        employee.setVisible(true);
        employee.setPreferredSize(getMaximumSize());
        employee.setClosable(true);
        try {
            employee.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
//dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

//        jdp.removeAll();
//        lib_obj = new library.library(this, true);
//        jdp.add(lib_obj);
//        lib_obj.setVisible(true);
//        lib_obj.setPreferredSize(getMaximumSize());
//        lib_obj.setClosable(true);
//        try {
//            lib_obj.setMaximum(true);
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
//    jdp.removeAll();
//        Creditorsobj = new Account.Creditors(this, true);
//        jdp.add(Creditorsobj);
//        Creditorsobj.setVisible(true);
//        Creditorsobj.setPreferredSize(getMaximumSize());
//        Creditorsobj.setClosable(true);
//try {
//            Creditorsobj.setMaximum(true);
//        } catch (Exception e) {
//        }

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
//        jdp.removeAll();
//        purOrderObj = new Purchase.PurchaseOrder(this, true);
//        jdp.add(purOrderObj);
//        purOrderObj.setVisible(true);
//        purOrderObj.setPreferredSize(getMaximumSize());
//        purOrderObj.setClosable(true);
//        try {
//            purOrderObj.setMaximum(true);
//        } catch (Exception e) {
//        }
//        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
//        jdp.removeAll();
//        purReturnObj = new Purchase.PurchaseReturn(this, true);
//        jdp.add(purReturnObj);
//        purReturnObj.setVisible(true);
//        purReturnObj.setPreferredSize(getMaximumSize());
//        purReturnObj.setClosable(true);
//        try {
//            purReturnObj.setMaximum(true);
//        } catch (Exception e) {
//        }
//        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
//       jdp.removeAll();
//       purInvoiceObj=new Purchase.PurchaseInvoice(this, true);
//       jdp.add(purInvoiceObj);
//       purInvoiceObj.setVisible(true);
//       purInvoiceObj.setPreferredSize(getMaximumSize());
//       purInvoiceObj.setClosable(true);
//        // TODO add your handling code here:
//       try {
//            purInvoiceObj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
//       jdp.removeAll();
//       damageStockObj=new Stock.Damagestock(this, true);
//       jdp.add(damageStockObj);
//       damageStockObj.setVisible(true);
//       damageStockObj.setPreferredSize(getMaximumSize());
//       damageStockObj.setClosable(true);
//
//        try {
//            damageStockObj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
//       jdp.removeAll();
//       expiryStockObj=new Stock.ExpiryStock(this, true);
//       jdp.add(expiryStockObj);
//       expiryStockObj.setVisible(true);
//       expiryStockObj.setPreferredSize(getMaximumSize());
//       expiryStockObj.setClosable(true);
//
//        try {
//            expiryStockObj.setMaximum(true);
//        } catch (Exception e) {
//        }
//// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
//         jdp.removeAll();
//         BankObj=new master.Bank(this,true);
//       jdp.add(BankObj);
//       BankObj.setVisible(true);
//       BankObj.setPreferredSize(getMaximumSize());
//       BankObj.setClosable(true);
//try {
//            BankObj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
//         jdp.removeAll();
//           Bouncecheckobj=new Account.Bouncecheck(this, true);
//       jdp.add(Bouncecheckobj);
//       Bouncecheckobj.setVisible(true);
//       Bouncecheckobj.setPreferredSize(getMaximumSize());
//       Bouncecheckobj.setClosable(true);
//try {
//            Bouncecheckobj.setMaximum(true);
//        } catch (Exception e) {
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
//      jdp.removeAll();
//       CountersalesObj=new  Sales.Countersales(this, true);
//       jdp.add(  CountersalesObj);
//       CountersalesObj.setVisible(true);
//         CountersalesObj.setPreferredSize(getMaximumSize());
//         CountersalesObj.setClosable(true);
//try {
//            CountersalesObj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        jdp.removeAll();
//       SalesInvoiceobj=new  Sales.SalesInvoice(this, true);
//       jdp.add(  SalesInvoiceobj);
//      SalesInvoiceobj.setVisible(true);
//         SalesInvoiceobj.setPreferredSize(getMaximumSize());
//        SalesInvoiceobj.setClosable(true);
//try {
//            SalesInvoiceobj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:

//        jdp.removeAll();
//       Product_Informationobj=new  Stock.Product_Information(this, true);
//       jdp.add(  Product_Informationobj);
//      Product_Informationobj.setVisible(true);
//         Product_Informationobj.setPreferredSize(getMaximumSize());
//        Product_Informationobj.setClosable(true);
// try {
//            Product_Informationobj.setMaximum(true);
//        } catch (Exception e) {
//        }
//        
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed

//         jdp.removeAll();
//       BalanceSheetobj=new  Account.BalanceSheet(this, true);
//       jdp.add(  BalanceSheetobj);
//      BalanceSheetobj.setVisible(true);
//         BalanceSheetobj.setPreferredSize(getMaximumSize());
//        BalanceSheetobj.setClosable(true);
// try {
//            BalanceSheetobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
//         jdp.removeAll();
//       SalesRetailerobj=new  Sales.SalesRetailer(this, true);
//       jdp.add(  SalesRetailerobj);
//      SalesRetailerobj.setVisible(true);
//         SalesRetailerobj.setPreferredSize(getMaximumSize());
//        SalesRetailerobj.setClosable(true);
//
//        try {
//            SalesRetailerobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Limited Access!!!", "Demo Version 1.0 ", JOptionPane.INFORMATION_MESSAGE);
//        
//                    jdp.removeAll();
//       SalesReturnobj=new  Sales.SalesReturn(this, true);
//       jdp.add(  SalesReturnobj);
//      SalesReturnobj.setVisible(true);
//         SalesReturnobj.setPreferredSize(getMaximumSize());
//        SalesReturnobj.setClosable(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed

//                     jdp.removeAll();
//       CounterReturnobj=new  Sales.CounterReturn(this, true);
//       jdp.add(  CounterReturnobj);
//      CounterReturnobj.setVisible(true);
//         CounterReturnobj.setPreferredSize(getMaximumSize());
//        CounterReturnobj.setClosable(true);
//        try {
//            CounterReturnobj.setMaximum(true);
//        } catch (Exception e) {
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
//        Runtime r=Runtime.getRuntime();
//        try
//        {
//            r.exec("calc");
//        }
//        catch(Exception ex)
//        {
//             JOptionPane.showMessageDialog(rootPane, ex, "Error", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Runtime r = Runtime.getRuntime();

        try {
            r.exec("Notepad");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

//                 jdp.removeAll();
//       ProductPurchaseOrderobj=new  Purchase.ProductPurchaseOrder(this, true);
//       jdp.add(ProductPurchaseOrderobj);
//      ProductPurchaseOrderobj.setVisible(true);
//         ProductPurchaseOrderobj.setPreferredSize(getMaximumSize());
//        ProductPurchaseOrderobj.setClosable(true);
//        try {
//            ProductPurchaseOrderobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

//  jdp.removeAll();
//        ShortCutobj = new medicalstoremanagement.ShortCut(this, true);
//        jdp.add(ShortCutobj);
//        ShortCutobj.setVisible(true);
//        ShortCutobj.setPreferredSize(getMaximumSize());
//        ShortCutobj.setClosable(true);
//
//try {
//            ShortCutobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

//        jdp.removeAll();
//        ShortCutobj = new medicalstoremanagement.ShortCut(this, true);
//        jdp.add(ShortCutobj);
//        ShortCutobj.setVisible(true);
//        ShortCutobj.setPreferredSize(getMaximumSize());
//        ShortCutobj.setClosable(true);
//        try {
//            ShortCutobj.setMaximum(true);
//        } catch (Exception e) {
//        }// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

// jdp.removeAll();
//        materialInwardObj = new Stock.Materialinward(this, true);
//        
//        jdp.add(materialInwardObj);
//        materialInwardObj.setVisible(true);
//        materialInwardObj.setPreferredSize(getMaximumSize());
//        
//        materialInwardObj.setClosable(true);        
//try {
//            materialInwardObj.setMaximum(true);
//        } catch (Exception e) {
//        }
//// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed

//        jdp.removeAll();
//        QuickMaterialinwardobj = new QuickUpdation.QuickMaterialinward(this, true);
//        
//        jdp.add(QuickMaterialinwardobj);
//        QuickMaterialinwardobj.setVisible(true);
//        QuickMaterialinwardobj.setPreferredSize(getMaximumSize());
//        
//        QuickMaterialinwardobj.setClosable(true);
//try {
//            QuickMaterialinwardobj.setMaximum(true);
//        } catch (Exception e) {
//        }
//// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed

//        jdp.removeAll();
//        PendingAccountsobj = new Account.PendingAccounts(this, true);
//
//        jdp.add(PendingAccountsobj);
//        PendingAccountsobj.setVisible(true);
//        PendingAccountsobj.setPreferredSize(getMaximumSize());
//
//        PendingAccountsobj.setClosable(true);
//        try {
//            PendingAccountsobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed

//        jdp.removeAll();
//        CustomerCashPementobj = new Account.CustomerCashPement(this, true);
//
//        jdp.add(CustomerCashPementobj);
//        CustomerCashPementobj.setVisible(true);
//        CustomerCashPementobj.setPreferredSize(getMaximumSize());
//
//        CustomerCashPementobj.setClosable(true);
//        try {
//            CustomerCashPementobj.setMaximum(true);
//        } catch (Exception e) {
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed

//        jdp.removeAll();
//
//        ProductReportsobj = new Report.ProductReports(this, true);
//        jdp.add(ProductReportsobj);
//        ProductReportsobj.setVisible(true);
//        ProductReportsobj.setPreferredSize(getMaximumSize());
//        ProductReportsobj.setClosable(true);        // TODO add your handling code here:
//
//        try {
//            ProductReportsobj.setMaximum(true);
//        } catch (Exception e) {
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed

//        jdp.removeAll();
//        Vouchersobj = new Account.Vouchers(this, true);
//
//        jdp.add(Vouchersobj);
//        Vouchersobj.setVisible(true);
//        Vouchersobj.setPreferredSize(getMaximumSize());
//
//        Vouchersobj.setClosable(true);
//        try {
//            Vouchersobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed

//        jdp.removeAll();
//        CustomizedProductReportobj = new Report.CustomizedProductReport(this, true);
//
//        jdp.add(CustomizedProductReportobj);
//        CustomizedProductReportobj.setVisible(true);
//        CustomizedProductReportobj.setPreferredSize(getMaximumSize());
//
//        CustomizedProductReportobj.setClosable(true);
//        try {
//            CustomizedProductReportobj.setMaximum(true);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
//        jdp.removeAll();
//        StockReportsobj = new Report.StockReports(this, true);
//
//        jdp.add(StockReportsobj);
//        StockReportsobj.setVisible(true);
//        StockReportsobj.setPreferredSize(getMaximumSize());
//
//        StockReportsobj.setClosable(true);
//        try {
//            StockReportsobj.setMaximum(true);
//        } catch (Exception e) {
//        }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
//        jdp.removeAll();
//        AccountReportsobj = new Report.AccountReports(this, true);
//
//        jdp.add(AccountReportsobj);
//        AccountReportsobj.setVisible(true);
//        AccountReportsobj.setPreferredSize(getMaximumSize());
//
//        AccountReportsobj.setClosable(true);
//        try {
//            AccountReportsobj.setMaximum(true);
//        } catch (Exception e) {
//        }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed

//        jdp.removeAll();
//        BankAccountCrediteDebitStatusobj = new Account.BankAccountCrediteDebitStatus(this, true);
//
//        jdp.add(BankAccountCrediteDebitStatusobj);
//        BankAccountCrediteDebitStatusobj.setVisible(true);
//        BankAccountCrediteDebitStatusobj.setPreferredSize(getMaximumSize());
//
//        BankAccountCrediteDebitStatusobj.setClosable(true);
//        try {
//            BankAccountCrediteDebitStatusobj.setMaximum(true);
//        } catch (Exception e) {
//        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jdp.removeAll();
        vendor = new Vendor(this, true);
//        vehicle = new com.org.globaldesktop.master.Vehicle(this, true);
        jdp.add(vendor);
        vendor.setVisible(true);
        vendor.setPreferredSize(getMaximumSize());
        vendor.setClosable(true);
        try {
            vendor.setMaximum(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        // TODO add your handling code here:
//        invoiceEntry
        jdp.removeAll();
        invoiceEntry = new InvoiceEntry(this, true);
//        vehicle = new com.org.globaldesktop.master.Vehicle(this, true);
        jdp.add(invoiceEntry);
        invoiceEntry.setVisible(true);
        invoiceEntry.setPreferredSize(getMaximumSize());
        invoiceEntry.setClosable(true);
        try {
            vendor.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        // TODO add your handling code here:
//        invoiceEntry
        jdp.removeAll();
        printReport = new PrintReport(this, true);
//        vehicle = new com.org.globaldesktop.master.Vehicle(this, true);
        jdp.add(printReport);
        printReport.setVisible(true);
        printReport.setPreferredSize(getMaximumSize());
        printReport.setClosable(true);
        try {
            printReport.setMaximum(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdp;
    // End of variables declaration//GEN-END:variables
}
